name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.REPO_TASK}}:${{GITHUB_SHA}}

      - name: Deploy in EC2
        env: 
          PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }} 
          HOSTNAME: ${ { secrets.HOSTNAME }} 
          USER_NAME: ${ { secrets.USERNAME }} 
        run: sudo docker pull pchendla/${{secrets.REPO_TASK}}:${{GITHUB_SHA}}

      # - name: Set outputs
      #   id: vars
      #   run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      # - name: Check outputs
      #   run: echo ${{ steps.vars.outputs.sha_short }}
          